import "./globals.css";
import { Roboto } from "next/font/google";

const roboto = Roboto({
  weight: ["200", "300"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} flex h-screen w-screen items-center justify-center antialiased bg-gray-100`}
      >
        {children}
      </body>
    </html>
  );
}
